import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { renderAdapter, writeAdapter } from "../src/adapters/generate.js";
import { policyTemplate } from "../src/core/policy.js";

const temporary: string[] = [];
afterEach(async () => {
  await Promise.all(
    temporary
      .splice(0)
      .map((path) => rm(path, { recursive: true, force: true })),
  );
});

describe("adapter generation", () => {
  it("refuses to overwrite a hand-written AGENTS.md", async () => {
    const root = await mkdtemp(join(tmpdir(), "guardspec-ow-"));
    temporary.push(root);
    await writeFile(
      join(root, "AGENTS.md"),
      "# My hand-written rules\n",
      "utf8",
    );
    const policy = policyTemplate("test", []);
    await expect(writeAdapter(root, "agents", policy)).rejects.toThrow(
      "not generated by GuardSpec",
    );
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toBe(
      "# My hand-written rules\n",
    );
  });

  it("regenerates a file that GuardSpec previously generated", async () => {
    const root = await mkdtemp(join(tmpdir(), "guardspec-ow2-"));
    temporary.push(root);
    const policy = policyTemplate("test", []);
    await writeFile(
      join(root, "AGENTS.md"),
      renderAdapter("agents", policy),
      "utf8",
    );
    const target = await writeAdapter(root, "agents", policy);
    expect(target).toBe("AGENTS.md");
  });
});
