import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import type { Policy } from "../core/types.js";

function bulletRules(policy: Policy): string[] {
  return policy.rules.map((rule) => {
    const value =
      rule.value === undefined
        ? ""
        : `: ${Array.isArray(rule.value) ? rule.value.join(", ") : String(rule.value)}`;
    return `- [${rule.effect.toUpperCase()}] ${rule.kind} \`${rule.scope}\`${value}. Rule: ${rule.id}.`;
  });
}

function header(policy: Policy): string {
  return `<!-- Generated by GuardSpec from .agent-policy.yml. Review policy changes; do not edit generated copies as a source of truth. -->\n# Repository agent boundaries\n\nThis repository uses GuardSpec policy **${policy.name}**. Before changing files or running commands, use \`guardspec check\` or the GuardSpec MCP server.\n\n${bulletRules(policy).join("\n")}\n`;
}

export function adapterTarget(agent: string): string {
  const known: Record<string, string> = {
    agents: "AGENTS.md",
    claude: "CLAUDE.md",
    copilot: ".github/copilot-instructions.md",
    cursor: ".cursor/rules/guardspec.mdc",
    gemini: "GEMINI.md",
    opencode: "AGENTS.md",
  };
  const target = known[agent];
  if (!target)
    throw new Error(
      `Unsupported adapter '${agent}'. Supported: ${Object.keys(known).join(", ")}.`,
    );
  return target;
}

export function renderAdapter(agent: string, policy: Policy): string {
  if (agent === "cursor")
    return `---\ndescription: GuardSpec repository policy\nalwaysApply: true\n---\n\n${header(policy)}`;
  if (agent === "copilot")
    return `${header(policy)}\nFor path-specific agent instructions, keep the GuardSpec policy as the authoritative machine-readable source.\n`;
  return header(policy);
}

export async function writeAdapter(
  root: string,
  agent: string,
  policy: Policy,
): Promise<string> {
  const target = adapterTarget(agent);
  const absolute = resolve(root, target);
  await mkdir(dirname(absolute), { recursive: true });
  await writeFile(absolute, renderAdapter(agent, policy), "utf8");
  return target;
}
